---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: nginx-r-pol
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: nginx-r
  policy:
    semver:
      range: 1.0.x

