---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-r
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/nginx-r
      sourceRef:
        kind: GitRepository
        name: nginx-r
  interval: 1m0s
  releaseName: helm-nginx-r
  targetNamespace: default
  values:
    image:
      repository: jorgejsilva/nginx-r
      tag: "1.0"
    ingress:
      enabled: true
      className: "nginx"
      hosts:
      - host: nginx-r.150.165.254.151.nip.io
        paths:
        - path: /
          pathType: ImplementationSpecific
